// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bs.proto

package bs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddBookRequest struct {
	Book                 *AddBookRequest_BookInfo `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{0}
}

func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (m *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(m, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetBook() *AddBookRequest_BookInfo {
	if m != nil {
		return m.Book
	}
	return nil
}

type AddBookRequest_BookInfo struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	AddedBy              string   `protobuf:"bytes,4,opt,name=addedBy,proto3" json:"addedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest_BookInfo) Reset()         { *m = AddBookRequest_BookInfo{} }
func (m *AddBookRequest_BookInfo) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest_BookInfo) ProtoMessage()    {}
func (*AddBookRequest_BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{0, 0}
}

func (m *AddBookRequest_BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest_BookInfo.Unmarshal(m, b)
}
func (m *AddBookRequest_BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest_BookInfo.Marshal(b, m, deterministic)
}
func (m *AddBookRequest_BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest_BookInfo.Merge(m, src)
}
func (m *AddBookRequest_BookInfo) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest_BookInfo.Size(m)
}
func (m *AddBookRequest_BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest_BookInfo proto.InternalMessageInfo

func (m *AddBookRequest_BookInfo) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *AddBookRequest_BookInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddBookRequest_BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AddBookRequest_BookInfo) GetAddedBy() string {
	if m != nil {
		return m.AddedBy
	}
	return ""
}

type AddBookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{1}
}

func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (m *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(m, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{2}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	Books                []*ListBooksResponse_BookInfo `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{3}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*ListBooksResponse_BookInfo {
	if m != nil {
		return m.Books
	}
	return nil
}

type ListBooksResponse_BookInfo struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	AddedBy              string   `protobuf:"bytes,4,opt,name=addedBy,proto3" json:"addedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse_BookInfo) Reset()         { *m = ListBooksResponse_BookInfo{} }
func (m *ListBooksResponse_BookInfo) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse_BookInfo) ProtoMessage()    {}
func (*ListBooksResponse_BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{3, 0}
}

func (m *ListBooksResponse_BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse_BookInfo.Unmarshal(m, b)
}
func (m *ListBooksResponse_BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse_BookInfo.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse_BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse_BookInfo.Merge(m, src)
}
func (m *ListBooksResponse_BookInfo) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse_BookInfo.Size(m)
}
func (m *ListBooksResponse_BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse_BookInfo proto.InternalMessageInfo

func (m *ListBooksResponse_BookInfo) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *ListBooksResponse_BookInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListBooksResponse_BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ListBooksResponse_BookInfo) GetAddedBy() string {
	if m != nil {
		return m.AddedBy
	}
	return ""
}

type DelBookRequest struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelBookRequest) Reset()         { *m = DelBookRequest{} }
func (m *DelBookRequest) String() string { return proto.CompactTextString(m) }
func (*DelBookRequest) ProtoMessage()    {}
func (*DelBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{4}
}

func (m *DelBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBookRequest.Unmarshal(m, b)
}
func (m *DelBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBookRequest.Marshal(b, m, deterministic)
}
func (m *DelBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBookRequest.Merge(m, src)
}
func (m *DelBookRequest) XXX_Size() int {
	return xxx_messageInfo_DelBookRequest.Size(m)
}
func (m *DelBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelBookRequest proto.InternalMessageInfo

func (m *DelBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type DelBookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelBookResponse) Reset()         { *m = DelBookResponse{} }
func (m *DelBookResponse) String() string { return proto.CompactTextString(m) }
func (*DelBookResponse) ProtoMessage()    {}
func (*DelBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{5}
}

func (m *DelBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBookResponse.Unmarshal(m, b)
}
func (m *DelBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBookResponse.Marshal(b, m, deterministic)
}
func (m *DelBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBookResponse.Merge(m, src)
}
func (m *DelBookResponse) XXX_Size() int {
	return xxx_messageInfo_DelBookResponse.Size(m)
}
func (m *DelBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelBookResponse proto.InternalMessageInfo

func (m *DelBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindBookRequest struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindBookRequest) Reset()         { *m = FindBookRequest{} }
func (m *FindBookRequest) String() string { return proto.CompactTextString(m) }
func (*FindBookRequest) ProtoMessage()    {}
func (*FindBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{6}
}

func (m *FindBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindBookRequest.Unmarshal(m, b)
}
func (m *FindBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindBookRequest.Marshal(b, m, deterministic)
}
func (m *FindBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindBookRequest.Merge(m, src)
}
func (m *FindBookRequest) XXX_Size() int {
	return xxx_messageInfo_FindBookRequest.Size(m)
}
func (m *FindBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindBookRequest proto.InternalMessageInfo

func (m *FindBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type FindBookResponse struct {
	Book                 *FindBookResponse_Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FindBookResponse) Reset()         { *m = FindBookResponse{} }
func (m *FindBookResponse) String() string { return proto.CompactTextString(m) }
func (*FindBookResponse) ProtoMessage()    {}
func (*FindBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{7}
}

func (m *FindBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindBookResponse.Unmarshal(m, b)
}
func (m *FindBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindBookResponse.Marshal(b, m, deterministic)
}
func (m *FindBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindBookResponse.Merge(m, src)
}
func (m *FindBookResponse) XXX_Size() int {
	return xxx_messageInfo_FindBookResponse.Size(m)
}
func (m *FindBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindBookResponse proto.InternalMessageInfo

func (m *FindBookResponse) GetBook() *FindBookResponse_Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type FindBookResponse_Book struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	AddedBy              string   `protobuf:"bytes,4,opt,name=addedBy,proto3" json:"addedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindBookResponse_Book) Reset()         { *m = FindBookResponse_Book{} }
func (m *FindBookResponse_Book) String() string { return proto.CompactTextString(m) }
func (*FindBookResponse_Book) ProtoMessage()    {}
func (*FindBookResponse_Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb5e2b918995edf, []int{7, 0}
}

func (m *FindBookResponse_Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindBookResponse_Book.Unmarshal(m, b)
}
func (m *FindBookResponse_Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindBookResponse_Book.Marshal(b, m, deterministic)
}
func (m *FindBookResponse_Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindBookResponse_Book.Merge(m, src)
}
func (m *FindBookResponse_Book) XXX_Size() int {
	return xxx_messageInfo_FindBookResponse_Book.Size(m)
}
func (m *FindBookResponse_Book) XXX_DiscardUnknown() {
	xxx_messageInfo_FindBookResponse_Book.DiscardUnknown(m)
}

var xxx_messageInfo_FindBookResponse_Book proto.InternalMessageInfo

func (m *FindBookResponse_Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *FindBookResponse_Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FindBookResponse_Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FindBookResponse_Book) GetAddedBy() string {
	if m != nil {
		return m.AddedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddBookRequest)(nil), "AddBookRequest")
	proto.RegisterType((*AddBookRequest_BookInfo)(nil), "AddBookRequest.BookInfo")
	proto.RegisterType((*AddBookResponse)(nil), "AddBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "ListBooksResponse")
	proto.RegisterType((*ListBooksResponse_BookInfo)(nil), "ListBooksResponse.BookInfo")
	proto.RegisterType((*DelBookRequest)(nil), "DelBookRequest")
	proto.RegisterType((*DelBookResponse)(nil), "DelBookResponse")
	proto.RegisterType((*FindBookRequest)(nil), "FindBookRequest")
	proto.RegisterType((*FindBookResponse)(nil), "FindBookResponse")
	proto.RegisterType((*FindBookResponse_Book)(nil), "FindBookResponse.Book")
}

func init() { proto.RegisterFile("bs.proto", fileDescriptor_9fb5e2b918995edf) }

var fileDescriptor_9fb5e2b918995edf = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xee, 0x4a, 0x85, 0x32, 0x24, 0xb4, 0xcc, 0x81, 0x6c, 0xea, 0x85, 0x6c, 0x34, 0x21, 0x6a,
	0x36, 0x01, 0x9e, 0x40, 0x62, 0x4c, 0x4c, 0x3c, 0xe1, 0x0b, 0xd8, 0x66, 0x17, 0x21, 0x40, 0x17,
	0xd9, 0x72, 0xf0, 0x6d, 0x3c, 0x78, 0xf4, 0x6d, 0x7c, 0x21, 0xb3, 0xcb, 0x96, 0x9f, 0x62, 0xc2,
	0x49, 0x6f, 0x33, 0xdf, 0x7e, 0x9d, 0x9f, 0x6f, 0xbe, 0x42, 0x90, 0x6a, 0xbe, 0x5c, 0xa9, 0x5c,
	0xb1, 0x4f, 0x02, 0xcd, 0x3b, 0x21, 0x86, 0x4a, 0xcd, 0x46, 0xf2, 0x6d, 0x2d, 0x75, 0x8e, 0xb7,
	0xe0, 0xa7, 0x4a, 0xcd, 0x28, 0xe9, 0x90, 0x6e, 0xa3, 0x4f, 0xf9, 0xe1, 0x33, 0x37, 0xf1, 0x63,
	0x36, 0x56, 0x23, 0xcb, 0x8a, 0x05, 0x04, 0x05, 0x82, 0x08, 0xfe, 0x54, 0xa7, 0x99, 0xfd, 0xb2,
	0x3e, 0xb2, 0xb1, 0xc1, 0xb2, 0x64, 0x21, 0xe9, 0xd9, 0x06, 0x33, 0x31, 0xb6, 0xa1, 0x9a, 0xac,
	0xf3, 0x89, 0x5a, 0xd1, 0x8a, 0x45, 0x5d, 0x86, 0x14, 0x6a, 0x89, 0x10, 0x52, 0x0c, 0xdf, 0xa9,
	0x6f, 0x1f, 0x8a, 0x94, 0xdd, 0x40, 0xb8, 0x1d, 0x43, 0x2f, 0x55, 0xa6, 0xa5, 0x21, 0x2f, 0xa4,
	0xd6, 0xc9, 0xab, 0x74, 0xfd, 0x8a, 0x94, 0x21, 0x44, 0x4f, 0x53, 0x9d, 0x1b, 0xb6, 0x76, 0x53,
	0xb3, 0x2f, 0x02, 0xad, 0x3d, 0xd0, 0xd5, 0xe8, 0xc1, 0xb9, 0x59, 0x42, 0x53, 0xd2, 0xa9, 0x74,
	0x1b, 0xfd, 0x0b, 0x7e, 0x44, 0xd9, 0xad, 0xbb, 0x61, 0xfe, 0xd3, 0xbe, 0x97, 0xd0, 0xbc, 0x97,
	0xf3, 0xfd, 0xab, 0xfc, 0xd2, 0xcb, 0xa8, 0xb2, 0x65, 0x9d, 0x54, 0xe5, 0x0a, 0xc2, 0x87, 0x69,
	0x26, 0x4e, 0xd5, 0xfc, 0x20, 0x10, 0xed, 0x78, 0xae, 0xea, 0xf5, 0x81, 0x25, 0xda, 0xbc, 0x4c,
	0xb0, 0x2a, 0x39, 0x43, 0xbc, 0x80, 0x6f, 0xb2, 0xbf, 0x13, 0xa7, 0xff, 0x4d, 0xa0, 0x6e, 0x5a,
	0x3c, 0x4f, 0xe4, 0x7c, 0x8c, 0x1c, 0x6a, 0xce, 0x1a, 0x18, 0x96, 0xbc, 0x1a, 0x47, 0xbc, 0xe4,
	0x1a, 0xe6, 0xe1, 0x00, 0x82, 0xe2, 0xca, 0xd8, 0xe2, 0x65, 0xa3, 0xc4, 0x78, 0xec, 0x01, 0xe6,
	0x99, 0x26, 0x4e, 0x69, 0x0c, 0xf9, 0xe1, 0x65, 0xe2, 0x88, 0x97, 0x8e, 0xc0, 0x3c, 0xec, 0x41,
	0x50, 0x68, 0x84, 0x11, 0x2f, 0xe9, 0x1e, 0xb7, 0x8e, 0x04, 0x64, 0x5e, 0x5a, 0xb5, 0x3f, 0xe4,
	0xe0, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x24, 0x34, 0x56, 0x9c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookShelfClient is the client API for BookShelf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookShelfClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	ListBook(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
	DelBook(ctx context.Context, in *DelBookRequest, opts ...grpc.CallOption) (*DelBookResponse, error)
	FindBook(ctx context.Context, in *FindBookRequest, opts ...grpc.CallOption) (*FindBookResponse, error)
}

type bookShelfClient struct {
	cc *grpc.ClientConn
}

func NewBookShelfClient(cc *grpc.ClientConn) BookShelfClient {
	return &bookShelfClient{cc}
}

func (c *bookShelfClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, "/BookShelf/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookShelfClient) ListBook(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/BookShelf/ListBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookShelfClient) DelBook(ctx context.Context, in *DelBookRequest, opts ...grpc.CallOption) (*DelBookResponse, error) {
	out := new(DelBookResponse)
	err := c.cc.Invoke(ctx, "/BookShelf/DelBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookShelfClient) FindBook(ctx context.Context, in *FindBookRequest, opts ...grpc.CallOption) (*FindBookResponse, error) {
	out := new(FindBookResponse)
	err := c.cc.Invoke(ctx, "/BookShelf/FindBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookShelfServer is the server API for BookShelf service.
type BookShelfServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	ListBook(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	DelBook(context.Context, *DelBookRequest) (*DelBookResponse, error)
	FindBook(context.Context, *FindBookRequest) (*FindBookResponse, error)
}

// UnimplementedBookShelfServer can be embedded to have forward compatible implementations.
type UnimplementedBookShelfServer struct {
}

func (*UnimplementedBookShelfServer) AddBook(ctx context.Context, req *AddBookRequest) (*AddBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (*UnimplementedBookShelfServer) ListBook(ctx context.Context, req *ListBooksRequest) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBook not implemented")
}
func (*UnimplementedBookShelfServer) DelBook(ctx context.Context, req *DelBookRequest) (*DelBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelBook not implemented")
}
func (*UnimplementedBookShelfServer) FindBook(ctx context.Context, req *FindBookRequest) (*FindBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBook not implemented")
}

func RegisterBookShelfServer(s *grpc.Server, srv BookShelfServer) {
	s.RegisterService(&_BookShelf_serviceDesc, srv)
}

func _BookShelf_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookShelfServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookShelf/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookShelfServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookShelf_ListBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookShelfServer).ListBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookShelf/ListBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookShelfServer).ListBook(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookShelf_DelBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookShelfServer).DelBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookShelf/DelBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookShelfServer).DelBook(ctx, req.(*DelBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookShelf_FindBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookShelfServer).FindBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookShelf/FindBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookShelfServer).FindBook(ctx, req.(*FindBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookShelf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BookShelf",
	HandlerType: (*BookShelfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookShelf_AddBook_Handler,
		},
		{
			MethodName: "ListBook",
			Handler:    _BookShelf_ListBook_Handler,
		},
		{
			MethodName: "DelBook",
			Handler:    _BookShelf_DelBook_Handler,
		},
		{
			MethodName: "FindBook",
			Handler:    _BookShelf_FindBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bs.proto",
}
